### ISSUE TITLE
Docker Compose / Docker Stack File Creation

### ISSUE THREAD

**Issue by weselben** [weselben/freshware#70]
Create docker-compose.yml for local development and testing.
What it does: Defines a multi-container (in this case, single-container but with explicit settings) application for easy setup. This file can directly be used with docker stack deploy for production.

```
version: '3.8' # Use a recent Compose file format

services:
  dsm-controller:
    build:
      context: . # Build from current directory where Dockerfile resides
      dockerfile: Dockerfile
    image: yourusername/dsm-controller:latest # Name for your image
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      # Mount the Docker socket from the host into the container.
      # THIS IS CRITICAL for the controller to interact with the Docker daemon.
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Define environment variables used by your FastAPI app
      - API_LOGIN_USERNAME=admin
      - API_LOGIN_PASSWORD=supersecurepassword
    deploy:
      # If deploying as a stack, ensure it only runs on a manager node
      placement:
        constraints:
          - node.role == manager
      # Configure replicas if this was a scalable service, but for a controller, usually 1
      replicas: 1
      restart_policy:
        condition: on-failure # Always restart if it crashes
```
